//
//  MenuRouter.swift
//  HammerTestApp
//
//  Created by Илья Дубенский on 03.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MenuRoutingLogic {
    func routeToItemDetails(value: Int)
}

protocol MenuDataPassing {
    var dataStore: MenuDataStore? { get }
}

class MenuRouter: NSObject, MenuRoutingLogic, MenuDataPassing {
    
    weak var viewController: MenuViewController?
    var dataStore: MenuDataStore?
    
    // MARK: Routing
    func routeToItemDetails(value: Int) {
        let destinationVC = ItemDetailsViewController()
        guard let dataStore = dataStore,
              let viewController = viewController,
              var destinationDS = destinationVC.router?.dataStore
        else { fatalError("Fail route to detail") }
        navigateToItemDetails(source: viewController, destination: destinationVC)
        passDataToItemDetails(source: dataStore, destination: &destinationDS, IndexPathRow: value)
    }
    
    // MARK: Navigation
    func navigateToItemDetails(source: MenuViewController,
                               destination: ItemDetailsViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    func passDataToItemDetails(source: MenuDataStore,
                               destination: inout ItemDetailsDataStore,
                               IndexPathRow: Int) {
        destination.item = source.items[IndexPathRow]
    }
}
