//
//  MenuModels.swift
//  HammerTestApp
//
//  Created by Илья Дубенский on 03.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias ItemCellViewModel = Menu.ShowItems.ViewModel.ItemCellViewModel

protocol ItemCellViewModelProtocol {
    var identifier: String { get }
    var height: Double { get }
    var itemName: String { get }
    var itemDescription: String { get }
    var itemImageURL: URL { get }
    var itemPrice: Double { get }
    var itemCategory: String { get }
    init(item: Item)
}

enum Menu {
    // MARK: Use cases
    enum ShowItems {
        struct Response {
            let items: [Item]
        }
        
        struct ViewModel {
            struct ItemCellViewModel: ItemCellViewModelProtocol {
                var identifier: String {
                    "ItemCell"
                }
                
                var height: Double {
                    150
                }
                
                var itemPrice: Double {
                    item.price
                }
                
                var itemName: String {
                    item.title
                }
                
                var itemDescription: String {
                    item.description
                }
                
                var itemImageURL: URL {
                    item.image
                }

                var itemCategory: String {
                    item.category.rawValue
                }
                
                private let item: Item
                
                init(item: Item) {
                    self.item = item
                }
            }

            let rows: [ItemCellViewModelProtocol]
        }
    }
}
