//
//  MenuPresenter.swift
//  HammerTestApp
//
//  Created by Илья Дубенский on 03.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol MenuPresentationLogic {
    func presentItems(response: Menu.ShowItems.Response)
}

class MenuPresenter: MenuPresentationLogic {
    
    weak var viewController: MenuDisplayLogic?
    
    func presentItems(response: Menu.ShowItems.Response) {
        let rows: [ItemCellViewModelProtocol] = response.items.map {
            ItemCellViewModel(item: $0)
        }
        let viewModel = Menu.ShowItems.ViewModel(rows: rows)
        viewController?.displayMenu(viewModel: viewModel)
    }
}
