//
//  MenuInteractor.swift
//  HammerTestApp
//
//  Created by Илья Дубенский on 03.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol MenuBusinessLogic {
    func fetchItems()
}

protocol MenuDataStore {
    var items: [Item] { get }

}

class MenuInteractor: MenuBusinessLogic, MenuDataStore {
    
    var presenter: MenuPresentationLogic?
    var items: [Item] = []
    
    func fetchItems() {
        NetworkManager.shared.fetchData([Item].self,
                                        from: Link.fakeDataProducts.rawValue) { [weak self] result in
            switch result {
            case .success(let items):
                self?.items = items
                let response = Menu.ShowItems.Response(items: items)
                self?.presenter?.presentItems(response: response)
            case .failure(let error):
                print(error)
            }
        }
    }
}
