//
//  ItemDetailsRouter.swift
//  HammerTestApp
//
//  Created by Илья Дубенский on 04.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ItemDetailsRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ItemDetailsDataPassing {
    var dataStore: ItemDetailsDataStore? { get }
}

class ItemDetailsRouter: NSObject, ItemDetailsRoutingLogic, ItemDetailsDataPassing {
    
    weak var viewController: ItemDetailsViewController?
    var dataStore: ItemDetailsDataStore?
}
