//
//  ItemDetailsInteractor.swift
//  HammerTestApp
//
//  Created by Илья Дубенский on 04.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ItemDetailsBusinessLogic {
    func provideItemDetails()
}

protocol ItemDetailsDataStore {
    var item: Item? { get set }
}

class ItemDetailsInteractor: ItemDetailsBusinessLogic, ItemDetailsDataStore {
    var item: Item?
    var presenter: ItemDetailsPresentationLogic?
    var worker: ItemDetailsWorker?
    
    func provideItemDetails() {
        worker = ItemDetailsWorker()
//        let imageData = worker?.getImage(from: item?.image)

        let response = ItemDetails.ShowDetails.Response(title: item?.title,
                                                        price: item?.price,
                                                        description: item?.description,
                                                        category: item?.category,
                                                        imageURL: item?.image)

        presenter?.presentItemDetails(response: response)

    }
}
