//
//  ItemDetailsModels.swift
//  HammerTestApp
//
//  Created by Илья Дубенский on 04.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum ItemDetails {
 
    // MARK: Use cases
    enum ShowDetails {
        struct Response {
            let title: String?
            let price: Double?
            let description: String?
            let category: Category?
            let imageURL: URL?
        }
        
        struct ViewModel {
            let title: String
            let price: String
            let description: String
            let category: Category
            let imageURL: URL
        }
    }
}
