//
//  ContactsInteractor.swift
//  HammerTestApp
//
//  Created by Илья Дубенский on 03.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ContactsBusinessLogic {
    func doSomething(request: Contacts.Something.Request)
}

protocol ContactsDataStore {
    
}

class ContactsInteractor: ContactsBusinessLogic, ContactsDataStore {
    
    var presenter: ContactsPresentationLogic?
    var worker: ContactsWorker?
    
    func doSomething(request: Contacts.Something.Request) {
        worker = ContactsWorker()
        worker?.doSomeWork()
        
        let response = Contacts.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
