//
//  CartInteractor.swift
//  HammerTestApp
//
//  Created by Илья Дубенский on 03.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CartBusinessLogic {
    func doSomething(request: Cart.Something.Request)
}

protocol CartDataStore {
    
}

class CartInteractor: CartBusinessLogic, CartDataStore {
    
    var presenter: CartPresentationLogic?
    var worker: CartWorker?
    
    func doSomething(request: Cart.Something.Request) {
        worker = CartWorker()
        worker?.doSomeWork()
        
        let response = Cart.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
